---
- name: Gather basic facts
  ansible.builtin.setup:

- name: Check disk usage
  ansible.builtin.shell: df -h
  register: disk_usage
  changed_when: false

- name: Output disk usage
  ansible.builtin.debug:
    var: disk_usage.stdout



- name: Injected failing task
  ansible.builtin.shell: false
  register: injected_fail
  changed_when: false

- name: Fix injected failure
  ansible.builtin.shell: echo fixed
  changed_when: false
