[phases.setup]
nixPkgs = ["python311", "pip", "gcc", "pkg-config"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python opsPilot/app.py"
