[phases.setup]
nixPkgs = ["python311Full", "gcc", "pkg-config"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "python opsPilot/app.py"
