---
# Package Management Failure Scenario
# This playbook intentionally uses wrong package names to simulate failures
- name: Package Installation Failure Test
  hosts: all_servers
  become: yes
  gather_facts: yes

  tasks:
    - name: Install web server (WILL FAIL - wrong package name)
      package:
        name: "{{ wrong_package_name }}"
        state: present
      vars:
        wrong_package_name: "{{ 'httpd' if ansible_os_family == 'Debian' else 'apache2' }}"
      register: package_result
      failed_when: false  # Don't stop on failure for testing
      tags: [package_failure]

    - name: Show package installation result
      debug:
        var: package_result
      tags: [package_failure]

    - name: Install non-existent package (WILL FAIL)
      package:
        name: "totally-fake-package-that-does-not-exist"
        state: present
      register: fake_package_result
      failed_when: false
      tags: [fake_package]

    - name: Show fake package result
      debug:
        var: fake_package_result
      tags: [fake_package]

    - name: Try to install from wrong repository (WILL FAIL)
      apt:
        name: "some-enterprise-package"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      register: repo_result
      failed_when: false
      tags: [repo_failure]

    - name: Show repository failure result
      debug:
        var: repo_result
      when: ansible_os_family == "Debian"
      tags: [repo_failure]
