---
# Service Management Failure Scenario
# This playbook tries to manage non-existent services
- name: Service Management Failure Test
  hosts: all_servers
  become: yes
  gather_facts: yes

  tasks:
    - name: Try to start non-existent service (WILL FAIL)
      service:
        name: "fake-service-that-does-not-exist"
        state: started
      register: fake_service_result
      failed_when: false
      tags: [fake_service]

    - name: Show fake service result
      debug:
        var: fake_service_result
      tags: [fake_service]

    - name: Try to start service with wrong name (WILL FAIL)
      service:
        name: "{{ wrong_service_name }}"
        state: started
      vars:
        wrong_service_name: "{{ 'apache2' if ansible_os_family == 'RedHat' else 'httpd' }}"
      register: wrong_service_result
      failed_when: false
      tags: [wrong_service]

    - name: Show wrong service result
      debug:
        var: wrong_service_result
      tags: [wrong_service]

    - name: Try to enable service that doesn't exist (WILL FAIL)
      service:
        name: "nonexistent-daemon"
        enabled: yes
      register: enable_result
      failed_when: false
      tags: [enable_failure]

    - name: Show enable failure result
      debug:
        var: enable_result
      tags: [enable_failure]

    - name: Try systemctl command on non-systemd system (MAY FAIL)
      systemd:
        name: "some-service"
        state: started
      register: systemd_result
      failed_when: false
      tags: [systemd_failure]

    - name: Show systemd result
      debug:
        var: systemd_result
      tags: [systemd_failure]
