version: '3.8'

services:
  # Ubuntu 20.04 test server
  ubuntu-server:
    image: ubuntu:20.04
    container_name: healing-test-ubuntu
    hostname: ubuntu-server
    networks:
      - healing-test-net
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y openssh-server python3 python3-pip sudo &&
        mkdir -p /var/run/sshd &&
        echo 'root:testpass' | chpasswd &&
        echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config &&
        useradd -m -s /bin/bash testuser &&
        echo 'testuser:testpass' | chpasswd &&
        usermod -aG sudo testuser &&
        service ssh start &&
        tail -f /dev/null
      "
    ports:
      - "2201:22"
    volumes:
      - ./shared:/shared

  # CentOS 8 test server
  centos-server:
    image: centos:8
    container_name: healing-test-centos
    hostname: centos-server
    networks:
      - healing-test-net
    command: >
      bash -c "
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* &&
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* &&
        yum update -y &&
        yum install -y openssh-server python3 python3-pip sudo which &&
        ssh-keygen -A &&
        echo 'root:testpass' | chpasswd &&
        echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config &&
        useradd -m -s /bin/bash testuser &&
        echo 'testuser:testpass' | chpasswd &&
        usermod -aG wheel testuser &&
        /usr/sbin/sshd -D
      "
    ports:
      - "2202:22"
    volumes:
      - ./shared:/shared

  # Alpine Linux test server (lightweight)
  alpine-server:
    image: alpine:latest
    container_name: healing-test-alpine
    hostname: alpine-server
    networks:
      - healing-test-net
    command: >
      sh -c "
        apk update &&
        apk add openssh python3 py3-pip sudo bash &&
        ssh-keygen -A &&
        echo 'root:testpass' | chpasswd &&
        echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config &&
        adduser -D -s /bin/bash testuser &&
        echo 'testuser:testpass' | chpasswd &&
        echo 'testuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
        /usr/sbin/sshd -D
      "
    ports:
      - "2203:22"
    volumes:
      - ./shared:/shared

  # Ansible control node
  ansible-controller:
    image: python:3.9-slim
    container_name: healing-ansible-controller
    hostname: ansible-controller
    networks:
      - healing-test-net
    working_dir: /workspace
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y openssh-client sshpass &&
        pip install ansible paramiko &&
        tail -f /dev/null
      "
    volumes:
      - ../playbooks:/workspace/playbooks
      - ../healing-agent:/workspace/healing-agent
      - ./shared:/shared
      - ./ansible-config:/etc/ansible

networks:
  healing-test-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
